spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-product

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.newgrad.mall: debug
alibaba:
  cloud:
    access-key: LTAI5tDo8HRshjvuqJ7hrsRA
    secret-key: vcQC3J9DvSzsltDwUiQRBp5J8Dq6oB
    oss:
      endpoint: oss-us-west-1.aliyuncs.com
